/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://44la6a6zxnczlmkmhmvvsjq7sq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nslfly624ba5fgjzeud4mi57le",
    "aws_cognito_identity_pool_id": "us-east-1:5cce6429-ca4c-4f13-86bb-d3b33c2a56aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0XkFTAODP",
    "aws_user_pools_web_client_id": "3tvj71b15fjiug22dfothvjf8j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "commandcenterfc96277c366d45a5b59e9d78af1d733c160337-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
